onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - prisma
  - esbuild
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
allowBuilds:
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  prisma: set this to true or false
verifyDepsBeforeRun: false
